create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  first_name text not null default '',
  last_name text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  seller_id uuid not null references public.profiles (id) on delete restrict,
  title text not null,
  description text not null default '',
  image_url text,
  price numeric(12, 2) not null check (price >= 0),
  inventory integer not null default 0 check (inventory >= 0),
  status text not null default 'active' check (status in ('active', 'draft', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.profiles (id) on delete restrict,
  status text not null default 'pending'
    check (status in ('pending', 'paid', 'shipped', 'delivered', 'cancelled')),
  total_amount numeric(12, 2) not null check (total_amount >= 0),
  currency text not null default 'USD',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders (id) on delete cascade,
  product_id bigint references public.products (id) on delete set null,
  product_title text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12, 2) not null check (unit_price >= 0)
);

create index if not exists products_seller_id_idx on public.products (seller_id);
create index if not exists products_status_created_at_idx on public.products (status, created_at desc);
create index if not exists orders_customer_id_created_at_idx on public.orders (customer_id, created_at desc);
create index if not exists order_items_order_id_idx on public.order_items (order_id);

grant select on public.profiles to authenticated;
grant update (first_name, last_name) on public.profiles to authenticated;
grant select on public.products to anon, authenticated;
grant insert, update, delete on public.products to authenticated;
grant select, insert, update, delete on public.orders to authenticated;
grant select, insert, update, delete on public.order_items to authenticated;
grant usage, select on sequence public.products_id_seq, public.order_items_id_seq to authenticated;

create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin';
$$;

create or replace function public.create_profile_for_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, first_name, last_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'first_name', ''),
    coalesce(new.raw_user_meta_data ->> 'last_name', '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists create_profile_after_signup on auth.users;
create trigger create_profile_after_signup
  after insert on auth.users
  for each row execute function public.create_profile_for_user();

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

revoke update on public.profiles from authenticated;
grant update (first_name, last_name) on public.profiles to authenticated;

create policy "Users can read their own profile"
  on public.profiles for select to authenticated
  using (id = (select auth.uid()) or (select public.is_admin()));
create policy "Users can update their own profile"
  on public.profiles for update to authenticated
  using (id = (select auth.uid()) or (select public.is_admin()))
  with check (id = (select auth.uid()) or (select public.is_admin()));
create policy "Admins can manage profiles"
  on public.profiles for all to authenticated
  using ((select public.is_admin()))
  with check ((select public.is_admin()));

create policy "Anyone can view active products"
  on public.products for select to anon, authenticated
  using (status = 'active' or seller_id = (select auth.uid()) or (select public.is_admin()));
create policy "Sellers can create their own products"
  on public.products for insert to authenticated
  with check (
    seller_id = (select auth.uid())
    and (select auth.jwt() -> 'app_metadata' ->> 'role') = 'seller'
  );
create policy "Sellers and admins can update products"
  on public.products for update to authenticated
  using (
    (seller_id = (select auth.uid())
     and (select auth.jwt() -> 'app_metadata' ->> 'role') = 'seller')
    or (select public.is_admin())
  )
  with check (
    (seller_id = (select auth.uid())
     and (select auth.jwt() -> 'app_metadata' ->> 'role') = 'seller')
    or (select public.is_admin())
  );
create policy "Sellers and admins can delete products"
  on public.products for delete to authenticated
  using (
    (seller_id = (select auth.uid())
     and (select auth.jwt() -> 'app_metadata' ->> 'role') = 'seller')
    or (select public.is_admin())
  );
create policy "Admins can create products for any seller"
  on public.products for insert to authenticated
  with check ((select public.is_admin()));

create policy "Customers can read their orders and admins can read all"
  on public.orders for select to authenticated
  using (customer_id = (select auth.uid()) or (select public.is_admin()));
create policy "Admins can manage orders"
  on public.orders for all to authenticated
  using ((select public.is_admin()))
  with check ((select public.is_admin()));

create policy "Customers can read their order items and admins can read all"
  on public.order_items for select to authenticated
  using (
    exists (
      select 1 from public.orders
      where orders.id = order_items.order_id
        and (orders.customer_id = (select auth.uid()) or (select public.is_admin()))
    )
  );
create policy "Admins can manage order items"
  on public.order_items for all to authenticated
  using ((select public.is_admin()))
  with check ((select public.is_admin()));
